# Generated by Django 2.2.6 on 2019-10-03 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('required', models.BooleanField()),
                ('number_of_items', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Item category',
                'verbose_name_plural': 'Items categorys',
            },
        ),
        migrations.CreateModel(
            name='OpeningHours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=50)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
            options={
                'verbose_name': 'OpeningHours',
                'verbose_name_plural': 'OpeningHours',
            },
        ),
        migrations.CreateModel(
            name='RestaurantCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name': 'RestaurantCategory',
                'verbose_name_plural': 'RestaurantCategories',
            },
        ),
        migrations.CreateModel(
            name='Shopping',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('cnpj', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=50)),
                ('neighborhood', models.CharField(blank=True, max_length=50)),
                ('cep', models.CharField(max_length=8)),
                ('number', models.IntegerField()),
                ('phone', models.CharField(max_length=12)),
            ],
            options={
                'verbose_name': 'Shopping',
                'verbose_name_plural': 'Shoppings',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('cnpj', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('corporate_name', models.CharField(default=models.CharField(max_length=100), max_length=100)),
                ('store_number', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(max_length=11)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurants', to='restaurant_service.RestaurantCategory')),
                ('opening_hours', models.ManyToManyField(to='restaurant_service.OpeningHours')),
                ('shopping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurants', to='restaurant_service.Shopping')),
            ],
            options={
                'verbose_name': 'Restaurant',
                'verbose_name_plural': 'Restaurants',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='restaurant_service.Restaurant')),
            ],
            options={
                'verbose_name': 'Menu',
                'verbose_name_plural': 'Menus',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('value', models.FloatField()),
                ('description', models.CharField(blank=True, max_length=200)),
                ('preparation_time', models.DurationField(blank=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='restaurant_service.ItemCategory')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='restaurant_service.Menu')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
            },
        ),
        migrations.CreateModel(
            name='Complement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('value', models.FloatField(blank=True)),
                ('item_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complement_category', to='restaurant_service.ItemCategory')),
            ],
            options={
                'verbose_name': 'Complement category',
                'verbose_name_plural': 'Complements categorys',
            },
        ),
    ]
