# Generated by Django 2.2.5 on 2019-09-26 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OpeningHours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=50)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
            options={
                'verbose_name': 'OpeningHours',
                'verbose_name_plural': 'OpeningHours',
            },
        ),
        migrations.CreateModel(
            name='RestaurantCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name': 'RestaurantCategory',
                'verbose_name_plural': 'RestaurantCategories',
            },
        ),
        migrations.CreateModel(
            name='Shopping',
            fields=[
                ('cnpj', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=50)),
                ('neighborhood', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=50)),
                ('number', models.IntegerField()),
                ('phone', models.CharField(max_length=11)),
            ],
            options={
                'verbose_name': 'Shopping',
                'verbose_name_plural': 'Shoppings',
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('cnpj', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('number', models.IntegerField()),
                ('description', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=11)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurants', to='restaurant_service.RestaurantCategory')),
                ('opening_hours', models.ManyToManyField(to='restaurant_service.OpeningHours')),
                ('shopping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurants', to='restaurant_service.Shopping')),
            ],
            options={
                'verbose_name': 'Restaurant',
                'verbose_name_plural': 'Restaurants',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='restaurant_service.Restaurant')),
            ],
            options={
                'verbose_name': 'Menu',
                'verbose_name_plural': 'Menus',
            },
        ),
        migrations.CreateModel(
            name='ItemMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('value', models.FloatField()),
                ('description', models.CharField(max_length=200)),
                ('preparation_time', models.DurationField()),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_menu', to='restaurant_service.Menu')),
            ],
            options={
                'verbose_name': 'Item menu',
                'verbose_name_plural': 'Items menu',
            },
        ),
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('required', models.BooleanField()),
                ('number_of_items', models.IntegerField()),
                ('item_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_category', to='restaurant_service.ItemMenu')),
            ],
            options={
                'verbose_name': 'Item category',
                'verbose_name_plural': 'Items category',
            },
        ),
        migrations.CreateModel(
            name='CategoryOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('value', models.FloatField(blank=True)),
                ('item_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_option', to='restaurant_service.ItemCategory')),
            ],
            options={
                'verbose_name': 'Category option',
                'verbose_name_plural': 'Category options',
            },
        ),
    ]
