# Generated by Django 2.2.7 on 2019-11-17 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='corporate_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
