# Generated by Django 2.2.5 on 2019-09-26 21:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shopping',
            options={'ordering': ['created'], 'verbose_name': 'Shopping', 'verbose_name_plural': 'Shoppings'},
        ),
        migrations.AddField(
            model_name='shopping',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
