# Generated by Django 2.2.6 on 2019-10-03 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopping',
            name='cnpj',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
