# Generated by Django 2.2.5 on 2019-09-26 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_service', '0002_auto_20190926_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopping',
            name='phone',
            field=models.CharField(max_length=12),
        ),
    ]
