# Generated by Django 2.2.6 on 2019-10-04 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_service', '0002_auto_20191003_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='phone',
            field=models.CharField(max_length=12),
        ),
    ]
